server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

rate-limit:
  capacity: 10        # Maximum tokens in bucket
  refill-rate: 5      # Tokens added per second
  window-duration: PT1M # Not used in current implementation but available

logging:
  level:
    org.springframework.data.redis: DEBUG